---
booktitle: Proceedings of the Second International Workshop on Self-Supervised Learning
shortname: iwssl
volume: '159'
year: '2021'
start: 2021-08-13
end: 2021-08-14
published: 2022-04-27
url: https://proceedings.mlr.press
location: Cambridge, Massachusetts, USA
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: IWSSL-2021
month: 0
cycles: false
bibtex_editor: Th\'orisson, Kristinn R. and Robertson, Paul
editor:
- given: Kristinn R.
  family: Thórisson
- given: Paul
  family: Robertson
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Second International Workshop on Self-Supervised Learning
    Held in Virtual on 13-14 August 2021

  Published as Volume 159 by the Proceedings of Machine Learning Research on 27 April 2022.

  Volume Edited by:
    Kristinn R. Thórisson
    Paul Robertson

  Series Editors:
    Neil D. Lawrence
date_str: 13--14 Aug
author:
  name: PMLR
baseurl: "/v159"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v159
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v159
email: ''
conference:
  name: International Workshop on Self-Supervised Learning
  url:
  location: Virtual
  dates:
  - 2021-08-13
  - 2021-08-14
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/home/markus/repos/mlresearch/v159/IWSSL2021.bib"
# Site settings
# Original source:  /home/markus/repos/mlresearch/v159/IWSSL2021.bib
